OdalysProject.Web/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OdalysProject.Web.Interfaces;
using OdalysProject.Web.Models;

namespace OdalysProject.Web.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;

        public CategoryController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository ?? throw new ArgumentNullException(nameof(categoryRepository));
        }

        public async Task<IActionResult> Index()
        {
            return View(await _categoryRepository.GetAllAsync());
        }

        [HttpGet]

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Create(Category category)
        {
            if (ModelState.IsValid)
            {
                await _categoryRepository.CreateAsync(category);
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult GetBooks(int Id)
        {
            var result = _categoryRepository.GetBooks(Id);

            return View(result);
        }

        [HttpGet]

        public async Task<IActionResult> Delete(int? Id)
        {
            return View(await _categoryRepository.GetByIdAsync(Id.Value));
        }

        [HttpPost]


        public async Task<IActionResult> Delete(int Id)
        {
            if (ModelState.IsValid)
            {
                await _categoryRepository.DeleteAsync(Id);


            }

            return RedirectToAction(nameof(Index));

        }


        [HttpGet]

        public async Task<IActionResult> Update(int Id)
        {
            return View(await _categoryRepository.GetByIdAsync(Id));
        }

        [HttpPost]
        public async Task<IActionResult> Update(Category category)
        {
            if (ModelState.IsValid)
            {
                await _categoryRepository.UpdateAsync(category);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

OdalysProject.Web/Controllers/PublisherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OdalysProject.Web.Interfaces;
using OdalysProject.Web.Models;

namespace OdalysProject.Web.Controllers
{
    public class PublisherController : Controller
    {
        private readonly IPublisherRepository _publisherRepository;

        public PublisherController(IPublisherRepository publisherRepository)
        {
            _publisherRepository = publisherRepository ?? throw new ArgumentNullException(nameof(publisherRepository));
        }

        public async Task<IActionResult> Index()
        {
            return View(await _publisherRepository.GetAllAsync());
        }

        [HttpGet]

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Create(Publisher publisher)
        {
            if (ModelState.IsValid)
            {
                await _publisherRepository.CreateAsync(publisher);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]

        public async Task<IActionResult> Delete(int? Id)
        {
            return View(await _publisherRepository.GetByIdAsync(Id.Value));
        }

        [HttpPost]


        public async Task<IActionResult> Delete(int Id)
        {
            if (ModelState.IsValid)
            {
                await _publisherRepository.DeleteAsync(Id);


            }

            return RedirectToAction(nameof(Index));

        }
    }
}

OdalysProject.Web/Controllers/RentBookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using OdalysProject.Web.Data;
using OdalysProject.Web.Interfaces;
using OdalysProject.Web.Models;

namespace OdalysProject.Web.Controllers
{
    public class RentBookController : Controller
    {
        private readonly IRentBookRepository _rentBookRepository;
        private readonly ApplicationDbContext _applicationDbContext;

        public RentBookController(IRentBookRepository rentBookRepository, ApplicationDbContext applicationDbContext)
        {
            _rentBookRepository = rentBookRepository ?? throw new ArgumentNullException(nameof(rentBookRepository));
            _applicationDbContext = applicationDbContext ?? throw new ArgumentNullException(nameof(applicationDbContext));
        }

        public async Task<IActionResult> Index()
        {
            return View(await _rentBookRepository.GetAllAsync());
        }

        [HttpGet]

        public IActionResult Create()
        {
            List<SelectListItem> books = (from i in _applicationDbContext.Book.ToList()
                                               select new SelectListItem
                                               {
                                                   Text = i.Name,
                                                   Value = i.BookId.ToString()
                                               }).ToList();

            ViewBag.Books = books;


            List<SelectListItem> students = (from i in _applicationDbContext.Student.ToList()
                                               select new SelectListItem
                                               {
                                                   Text = i.StudentNumber,
                                                   Value = i.StudentId.ToString()
                                               }).ToList();

            ViewBag.Students = students;

            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Create(RentBook rentBook)
        {
            if (ModelState.IsValid)
            {
                await _rentBookRepository.CreateAsync(rentBook);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

OdalysProject.Web/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using OdalysProject.Web.Interfaces;
using OdalysProject.Web.Models;

namespace OdalysProject.Web.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentRepository _studentRepository;

        public StudentController(IStudentRepository studentRepository)
        {
            _studentRepository = studentRepository ?? throw new ArgumentNullException(nameof(studentRepository));
        }

        public async Task<IActionResult> Index()
        {
            return View(await _studentRepository.GetAllAsync());
        }

        public IActionResult GetRentBook(int Id)
        {
            var result = _studentRepository.GetRentBook(Id);

            return View(result);
        }

        [HttpGet]

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]

        public async Task<IActionResult> Create(Student student)
        {
            if (ModelState.IsValid)
            {
                await _studentRepository.CreateAsync(student);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

OdalysProject.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - Odalys Project</title>
    <link rel="icon" href="~/ODALYS-GROUPE.jpg" />
    <link href="~/dist/css/dataTables.css" rel="stylesheet" />
    <link href="~/dist/css/styles.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>

</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        @Html.ActionLink("Odalys Project", "Index", "Home", null, new { @class = "navbar-brand" })
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>
        <partial name="_LoginPartial" />

        <!-- Navbar-->

    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">

                        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Sayfalar
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-parent="#sidenavAccordion">
                                <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">

                                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">

                                        Kitaplar
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            @Html.ActionLink("Kitap Listesi", "Index", "Book", null, new { @class = "nav-link" })
                                            @Html.ActionLink("Yeni Kitap Oluştur", "Create", "Book", null, new { @class = "nav-link" })

                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                                        Kategoriler
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">
                                            @Html.ActionLink("Kategori Listesi", "Index", "Category", null, new { @class = "nav-link" })
                                            @Html.ActionLink("Yeni Kategori Oluştur", "Create", "Category", null, new { @class = "nav-link" })


                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError1" aria-expanded="false" aria-controls="pagesCollapseError1">
                                        Yazarlar
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseError1" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">


                                            @Html.ActionLink("Yazar Listesi", "Index", "Author", null, new { @class = "nav-link" })

                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError2" aria-expanded="false" aria-controls="pagesCollapseError2">
                                        Yayınevleri
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseError2" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">


                                            @Html.ActionLink("Yayınevi Listesi", "Index", "Publisher", null, new { @class = "nav-link" })
                                            @Html.ActionLink("Yeni Yayınevi Oluştur", "Create", "Publisher", null, new { @class = "nav-link" })

                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError3" aria-expanded="false" aria-controls="pagesCollapseError3">
                                        Öğrenciler
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseError3" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">

                                            @Html.ActionLink("Öğrenci Listesi", "Index", "Student", null, new { @class = "nav-link" })
                                            @Html.ActionLink("Yeni Öğrenci Oluştur", "Create", "Student", null, new { @class = "nav-link" })

                                        </nav>
                                    </div>
                                    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#pagesCollapseError4" aria-expanded="false" aria-controls="pagesCollapseError4">
                                        Kiralık Kitap
                                        <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                                    </a>
                                    <div class="collapse" id="pagesCollapseError4" aria-labelledby="headingOne" data-parent="#sidenavAccordionPages">
                                        <nav class="sb-sidenav-menu-nested nav">

                                            @Html.ActionLink("Kiralanan Kitaplar", "Index", "RentBook", null, new { @class = "nav-link" })
                                            @Html.ActionLink("Yeni Kiralama Oluştur", "Create", "RentBook", null, new { @class = "nav-link" })

                                        </nav>
                                    </div>




                                </nav>
                            </div>
                        }
                        else
                        {

                        }

                    </div>
                </div>

            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                @RenderBody()
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Tüm Hakları Saklıdır! &copy; Odalys Project @DateTime.Now.Year</div>
                        <div>
                            @Html.ActionLink("Gizlilik", "Privacy", "Home")
                            &middot;
                            @Html.ActionLink("Şartlar & Koşullar", "Privacy", "Home")
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/dist/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/dist/assets/demo/chart-area-demo.js"></script>
    <script src="~/dist/assets/demo/chart-bar-demo.js"></script>
    <script src="~/dist/assets/demo/dataTables.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="~/dist/assets/demo/datatables-demo.js"></script>



    @RenderSection("Scripts", required: false)

</body>
</html>